import type { Metadata } from "next";
import "./globals.scss";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
    <head>
        <link rel="manifest" href="/manifest.json" />
    </head>
      <body className="font-default-400 container">
        {children}
      </body>
    </html>
  );
}
